<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

	</PropertyGroup>

	<ItemGroup>
		<Compile Update="AppStrings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AppStrings.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="AppStrings.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>AppStrings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
