<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

	</PropertyGroup>

	<ItemGroup>
		<Content Include="FFmpeg\avcodec-62.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\avdevice-62.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\avfilter-11.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\avformat-62.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\avutil-60.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\swresample-6.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\swscale-9.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
