<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<StartupObject>YiffBrowser.App</StartupObject>
		<PlatformTarget>x64</PlatformTarget>
		<ApplicationIcon>..\BaseFramework\Resources\Icons\YiffBrowserIcon.ico</ApplicationIcon>

		<Description>Yiff Browser</Description>
		<AssemblyTitle>Yiff Browser</AssemblyTitle>
		<AssemblyName>Yiff Browser</AssemblyName>

	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseFramework\BaseFramework.csproj" />
		<ProjectReference Include="..\YB.E621\YB.E621.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Costura.Fody" Version="6.0.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Fody" Version="6.9.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
