<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<StartupObject>YiffBrowser.App</StartupObject>
		<ApplicationIcon>..\BaseFramework\Resources\Icons\YiffBrowserIcon.ico</ApplicationIcon>

		<PlatformTarget>AnyCPU</PlatformTarget>
		<Prefer32Bit>false</Prefer32Bit>

		<Description>Yiff Browser</Description>
		<AssemblyTitle>Yiff Browser</AssemblyTitle>
		<AssemblyName>Yiff Browser</AssemblyName>

	</PropertyGroup>

	<ItemGroup>
	  <None Remove="FFmpeg\avcodec-62.dll" />
	  <None Remove="FFmpeg\avdevice-62.dll" />
	  <None Remove="FFmpeg\avfilter-11.dll" />
	  <None Remove="FFmpeg\avformat-62.dll" />
	  <None Remove="FFmpeg\avutil-60.dll" />
	  <None Remove="FFmpeg\swresample-6.dll" />
	  <None Remove="FFmpeg\swscale-9.dll" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="FFmpeg\avcodec-62.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="FFmpeg\avdevice-62.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="FFmpeg\avfilter-11.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="FFmpeg\avformat-62.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="FFmpeg\avutil-60.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="FFmpeg\swresample-6.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="FFmpeg\swscale-9.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseFramework\BaseFramework.csproj" />
		<ProjectReference Include="..\YB.E621\YB.E621.csproj" />
	</ItemGroup>

	<!--<ItemGroup>
		<PackageReference Include="Costura.Fody" Version="6.0.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Fody" Version="6.9.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>-->

</Project>
