using System.Windows.Markup;

[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Controls")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Converters")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Enums")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Events")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Extensions")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Helpers")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Interfaces")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Models")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Resources")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Services")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Utilities")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.ViewModels")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.ViewModelServices")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Views")]
[assembly: XmlnsDefinition("YiffBrowser.BaseFramework", "YiffBrowser.BaseFramework.Views.Dialogs")]

[assembly: XmlnsPrefix("YiffBrowser.BaseFramework", "bf")]
